version: '3.8'

services:
  db_test:
    container_name: db_test
    image: postgres:13
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - test_network

volumes:
  postgres_test_data:

networks:
  test_network:
